<?php
/**
 * Copyright © 2022 Trienekens Online. All rights reserved.
 *
 * @author Rudie Wang <rudie.wang.web@gmail.com>
 * @package Trienekens_CustomFee
 */
?>
<?php
/**
 * @var $block \Magento\Catalog\Block\Product\View
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
$costHelper = $objectManager->create('Trienekens\CustomFee\Helper\Data'); // Instance of Pricing Helper
?>
<div class="product-additional-cost">
    <?php if ($additionalCost = $block->getProduct()->getAttributeText('additional_cost')): ?>
        <?php if ($cost = $costHelper->getCost($additionalCost)): ?>
            <span><?= $costHelper->getFeeLabel() ?>: </span>
            <span class="price"><?= $priceHelper->currency($cost, true, false) ?></span>
        <?php endif; ?>
    <?php endif; ?>
</div>
