<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View $block */
?>
<?php
$_portohelper = $this->helper('Smartwave\Porto\Helper\Data');
$_product_label_config = $_portohelper->getConfig('porto_settings/product_label');

$_product = $block->getProduct()
?>
<?php
$product_label = "";
if($_product_label_config['sale_label']) {
    $orgprice = $_product->getPrice();
    $specialprice = $_product->getSpecialPrice();
    $specialfromdate = $_product->getSpecialFromDate();
    $specialtodate = $_product->getSpecialToDate();
    $today = time();
    if(!$specialprice)
        $specialprice = $orgprice;
    if($specialprice < $orgprice) {
        if((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))){
            if($_product_label_config['sale_label_percent']) {
                $save_percent = 100-round(($specialprice/$orgprice)*100);
                $product_label .= '<div class="product-label sale-label">'.'-'.$save_percent.'%'.'</div>';
            } else {
                $product_label .= '<div class="product-label sale-label">'.$_product_label_config['sale_label_text'].'</div>';
            }
        }
    }
}
if($_product_label_config['new_label']) {
    $now = date("Y-m-d");
    $newsFrom= substr($_product->getData('news_from_date'),0,10);
    $newsTo=  substr($_product->getData('news_to_date'),0,10);

    if ($newsTo != '' || $newsFrom != ''){
        if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)) {
            $product_label .= '<div class="product-label new-label">'.$_product_label_config['new_label_text'].'</div>';
        }
    }
}
if($product_label)
    echo '<div class="product-labels">'.$product_label.'</div>';
?>