<?php
/**
 * Copyright © 2022 Trienekens Online. All rights reserved.
 *
 * @author Rudie Wang <rudie.wang.web@gmail.com>
 * @package Trienekens_LinkedProduct
 */
?>
<?php
/**
 * @var $block \Trienekens\LinkedProduct\Block\Product\LinkedProducts
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
$costHelper = $objectManager->create('Trienekens\CustomFee\Helper\Data'); // Instance of Pricing Helper
$linkedProductIds = $block->getLinkedProducts();
?>
<?php if (count($linkedProductIds) > 1) : ?>
    <div class="product-linked-products products wrapper list  products-list">
        <p class="linked-product-title">Productvariaties</p>
        <ol class="products list items product-items">
            <?php
            $iterator = 0;
            foreach ($linkedProductIds as $linkedProductId) {
                if ($linkedProductId == $block->getProduct()->getId()) continue;

                /** @var $product \Magento\Catalog\Model\Product */
                $product = $block->getProductById($linkedProductId);
                $imageUrl = $block->getProductImageUrl($product);
                $iterator ++;
                ?>
                <li class="item product product-item <?= $iterator > 5 ? 'hide-item' : ''; ?>" <?= $iterator > 5 ? 'style="display:none;"' : ''; ?>>
                    <div class="product-item-info type0">
                        <?php // Product Image ?>
                        <div class="product photo product-item-photo">
                            <a href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() ?>">
                                <img class="product-image-photo default_image"
                                     data-src="<?= $imageUrl ?>"
                                     width="80" height="80" alt=""
                                     src="<?= $imageUrl ?>">
                            </a>
                        </div>

                        <div class="product details product-item-details">
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= $product->getProductUrl() ?>">
                                    <?= $product->getName() ?>
                                </a>
                            </strong>

                            <div class="product-info-stock-sku">
                                <?php if ($product->isAvailable()): ?>
                                    <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                                        <span class="label"><?php /* @escapeNotVerified */ echo __('Availability:') ?></span>
                                        <span><?= $block->getProductStocks($product) ?> <?php /* @escapeNotVerified */ echo __('In stock') ?></span>
                                    </div>
                                <?php else: ?>
                                    <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                                        <span class="label"><?php /* @escapeNotVerified */ echo __('Availability:') ?></span>
                                        <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
                                    </div>
                                <?php endif; ?>

                                <span class="stock-sku-separator">&nbsp;|&nbsp;</span>

                                <div class="product attribute sku">
                                    <strong class="type">EAN:</strong>
                                    <div class="value"><?= /* @noEscape */ $product->getSku() ?></div>
                                </div>
                            </div>
                        </div>

                        <div class="product-item-inner">
                            <?php
                            $priceWithoutTax = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getBaseAmount();
                            $priceWithTax = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getValue();
                            ?>
                            <div class="product-info-price">
                                <div class="price-box price-final_price">
                                        <span class="price-container price-final_price tax weee">
                                          <span data-label="Incl. BTW" class="price-wrapper price-including-tax">
                                            <span class="price"><?= $block->getCurrencyWithFormat($priceWithTax) ?></span>
                                          </span>
                                          <span data-label="Excl. BTW" class="price-wrapper price-excluding-tax">
                                            <span class="price"><?= $block->getCurrencyWithFormat($priceWithoutTax) ?></span>
                                          </span>
                                        </span>
                                </div>
                            </div>

                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($product->isSaleable()): ?>
                                        <form data-role="tocart-form" action="<?= $block->escapeUrl($block->getSubmitUrl($product)) ?>" method="post">
                                            <input type="hidden" name="product" value="<?php echo (int)$product->getId(); ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>

                                            <div class="box-tocart">
                                                <div class="fieldset">
                                                    <div class="field qty">
                                                        <div class="control">
                                                            <input type="text" name="qty" id="qty" maxlength="12" value="1" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                                                            <div class="qty-changer">
                                                                <a href="javascript:void(0)" class="qty-inc"><i class="porto-icon-up-dir"></i></a>
                                                                <a href="javascript:void(0)" class="qty-dec"><i class="porto-icon-down-dir"></i></a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="actions">
                                                        <button type="submit"
                                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart primary">
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <?php
            }
            ?>
        </ol>
        <?php if ($iterator > 5): ?>
            <div class="linked-product-show-more">
                <a href="javascript:void(0)">Bekijk meer <i class="porto-icon-down-open-big"></i></a>
            </div>
        <?php endif; ?>
    </div>
    <style>
        .product.media,
        .product-info-main {
            margin-bottom: 3rem;
        }
        .product-linked-products.products-list {
            border: solid 1px #e7e7e7;
            padding: 1.5em;
            margin: 0 0 3rem !important;
        }
        .product-linked-products.products-list .linked-product-title {
            font-size: 1.5em;
            font-weight: 600;
            color: #222529;
        }
        .product-linked-products.products-list .product-item {
            border-top: solid 1px #e7e7e7;
            margin: 0;
            padding: 10px 0;
        }
        .product-linked-products.products-list .product-item:last-child {
            border-bottom: none;
        }
        .product-linked-products.products-list .product-item-photo {
            flex: 0 0 70px;
            margin: 0 20px 0 0;
            min-height: 70px;
        }
        .product-linked-products .product-info-price,
        .product-linked-products .box-tocart {
            margin: 0;
        }
        .product-linked-products .product-info-stock-sku {
            font-size: .8571em;
            text-transform: uppercase;
            display: flex;
        }
        .product-linked-products .product-info-stock-sku .type {
            font-weight: initial;
        }
        .product-linked-products .stock span {
            font-weight: 400;
        }
        .product-linked-products .stock span + span {
            color: #00b900;
            font-weight: 700;
        }
        .product-linked-products .stock.unavailable span + span {
            color: #777777;
        }
        .product-linked-products .product.sku .value {
            display: inline-block;
            color: #777777;
            font-weight: 700;
        }
        .product-linked-products .box-tocart .actions {
            margin: 0 0 5px 0;
        }
        .product-linked-products .box-tocart .action.tocart {
            min-width: 48px;
            padding: 0;
            text-align: center;
        }
        .product-linked-products .box-tocart .action.tocart:before {
            margin: 0;
        }
        .product-linked-products .moved-add-to-links {
            display: none;
        }
        .product-linked-products .product-item-inner {
            width: 300px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .product-linked-products .linked-product-show-more {
            text-align: center;
            font-size: 1em;
            font-weight: 600;
            color: #222529;
            border-top: solid 1px #efefef;
            padding: 20px 15px 0 15px;
            margin-top: -15px;
        }
        .product-linked-products .linked-product-show-more > a {
            color: #222529;
        }

        @media (max-width: 768px) {
            .product-linked-products.products-list {
                padding: 20px 10px;
            }
            .product-linked-products.products-list .product-item-details {
                max-width: 100%;
            }
            .product-linked-products.products-list .product-item-photo,
            .product-linked-products.products-list .product-item-inner,
            .product-linked-products.products-list .stock-sku-separator,
            .product-linked-products.products-list .product.attribute.sku {
                display: none;
            }
            .product-linked-products.products-list .product-item {
                padding: 10px 0;
            }
        }
    </style>
    <script>
        require([
            'jquery'
        ], function ($) {
            $('.linked-product-show-more > a').click(function() {
                $('.product-linked-products.products-list .product-item.hide-item').toggle();
                if ($('.linked-product-show-more > a > i').hasClass('porto-icon-down-open-big')) {
                    $('.linked-product-show-more a').html('Bekijk minder <i class="porto-icon-up-open-big"></i>');
                } else {
                    $('.linked-product-show-more a').html('Bekijk meer <i class="porto-icon-down-open-big"></i>');
                }
            })
        });
    </script>
<?php endif; ?>